PACKAGE_NAME="seeed-voicecard"
PACKAGE_VERSION="0.3"

BUILT_MODULE_NAME[0]="snd-soc-seeed-voicecard"
BUILT_MODULE_LOCATION[0]=""
DEST_MODULE_LOCATION[0]="/kernel/sound/soc/codecs"

BUILT_MODULE_NAME[1]="snd-soc-ac108"
BUILT_MODULE_LOCATION[1]=""
DEST_MODULE_LOCATION[1]="/kernel/sound/soc/codecs"

BUILT_MODULE_NAME[2]="snd-soc-wm8960"
BUILT_MODULE_LOCATION[2]=""
DEST_MODULE_LOCATION[2]="/kernel/sound/soc/codecs"

# Оптимизировано для Orange Pi Zero 2W
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build ARCH=arm64 EXTRA_CFLAGS='-DCONFIG_SND_SOC_SEEED_VOICECARD -DCONFIG_ORANGEPI'"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"

AUTOINSTALL="yes"
